/* eslint-disable prettier/prettier */
import { Injectable } from '@nestjs/common';
import { Product } from './product.model';
import { CreateProductDto } from './dto/create-product.dto';

@Injectable()
export class ProductService {
  private products: Product[] = [
    {
      productName: 'Beautifull Seat',
      discountedPrice: 637.24,
      rawPrice: 937.78,
      reviewCount: 5,
      reviewStars: 4,
      miniminiDescription: 'Lorem ipsum sit dolor amet',
      miniDescription:
        'Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.',
      fullDescription: '<p>Lorem ipsum dolor sit amet...</p>',
      imgLink: 'https://pragmatic-linko.vercel.app/static/images/shop/2.jpg',
      additionalInformation:
        '<p>Curabitur auctor lacus eget lorem blandit...</p>',
    },
    {
      productName: 'Elegant Chair',
      discountedPrice: 453.2,
      rawPrice: 670.45,
      reviewCount: 8,
      reviewStars: 1,
      miniminiDescription: 'Lorem ipsum sit dolor amet',

      miniDescription:
        'Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.',
      fullDescription:
        '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor, nibh vel imperdiet pretium, augue ex rutrum sapien, sit amet rutrum purus libero pretium justo. Curabitur id nisi vitae metus ultricies condimentum. Fusce semper justo ipsum, rutrum rhoncus nulla scelerisque id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor nisl ornare ipsum ultricies, nec fermentum sem tincidunt. Donec arcu purus, tincidunt sed urna a, tristique gravida arcu. Nam ac tincidunt felis. Nam pulvinar ante ut efficitur pellentesque. Cras vel sodales turpis. Nunc fermentum sed sem quis egestas. Nullam ultrices eu diam quis viverra. Proin nec convallis risus. Maecenas efficitur dolor quis lacus scelerisque, vel rutrum nibh vestibulum. Nullam ante lorem, faucibus at convallis ut, ullamcorper sed lacus. In finibus orci eu nibh venenatis, imperdiet rhoncus felis accumsan. Cras a augue bibendum, consectetur enim mattis, vulputate leo.</p><p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Mauris vel facilisis tellus, sit amet cursus turpis. Duis ut consectetur nunc. Nulla viverra nulla vel mi pellentesque efficitur. Cras sit amet efficitur magna. Vestibulum ac ante ac magna feugiat scelerisque. Nullam condimentum gravida euismod. Donec rutrum egestas massa. Morbi venenatis dolor ac felis efficitur finibus. Vestibulum sed pellentesque sapien. Donec a rutrum leo, at ornare ligula. Nullam vel feugiat turpis, ac porta felis. Mauris hendrerit tincidunt ante sit amet vestibulum. Cras efficitur porta vulputate.</p>',
      imgLink:
        'https://img.edilportale.com/product-thumbs/b_Andreu-World_LICEO-OUTDOOR-SO1561_iprL3JtvLN.jpeg',
      additionalInformation:
        '<p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Ut posuere felis et ante pharetra ullamcorper. Maecenas sagittis nisl ac est porta volutpat. Praesent et mollis lorem, vel egestas augue. Aenean euismod auctor dapibus. Nullam sit amet urna erat. Duis euismod diam et nisl molestie dapibus. Sed non ligula vitae risus lacinia viverra id tempor neque. Sed tincidunt ultricies lacinia. Sed sed elit commodo, mattis mauris sed, imperdiet urna. Donec eu interdum ligula. In leo risus, vulputate sed diam nec, porta facilisis elit. Praesent sed sapien ultrices, vulputate nisl a, placerat nulla. Fusce mollis lectus orci. Pellentesque ut enim eleifend lacus dapibus vehicula. Sed mi neque, ullamcorper euismod diam quis, aliquet ultricies eros.</p><p>Pellentesque nunc purus, ultrices vitae nisi id, placerat mollis leo. Aenean egestas orci vel ipsum eleifend dapibus. Suspendisse a pellentesque dui, eu sodales massa. Donec condimentum arcu vitae augue consequat, in sodales enim scelerisque. Sed sodales eros sed porta cursus. Ut pellentesque bibendum tincidunt. Donec a molestie risus, eget consectetur nulla. Sed sed diam erat. Vestibulum velit ligula, eleifend eget sem ut, tristique sagittis neque. Phasellus eget velit nisi. Ut finibus ligula eget lectus aliquet, a ullamcorper velit facilisis.</p>',
    },
    {
      productName: 'Modern Table',
      discountedPrice: 789.99,
      rawPrice: 1050.0,
      reviewCount: 12,
      reviewStars: 2,
      miniminiDescription: 'Lorem ipsum sit dolor amet',

      miniDescription:
        'Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.',
      fullDescription:
        '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor, nibh vel imperdiet pretium, augue ex rutrum sapien, sit amet rutrum purus libero pretium justo. Curabitur id nisi vitae metus ultricies condimentum. Fusce semper justo ipsum, rutrum rhoncus nulla scelerisque id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor nisl ornare ipsum ultricies, nec fermentum sem tincidunt. Donec arcu purus, tincidunt sed urna a, tristique gravida arcu. Nam ac tincidunt felis. Nam pulvinar ante ut efficitur pellentesque. Cras vel sodales turpis. Nunc fermentum sed sem quis egestas. Nullam ultrices eu diam quis viverra. Proin nec convallis risus. Maecenas efficitur dolor quis lacus scelerisque, vel rutrum nibh vestibulum. Nullam ante lorem, faucibus at convallis ut, ullamcorper sed lacus. In finibus orci eu nibh venenatis, imperdiet rhoncus felis accumsan. Cras a augue bibendum, consectetur enim mattis, vulputate leo.</p><p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Mauris vel facilisis tellus, sit amet cursus turpis. Duis ut consectetur nunc. Nulla viverra nulla vel mi pellentesque efficitur. Cras sit amet efficitur magna. Vestibulum ac ante ac magna feugiat scelerisque. Nullam condimentum gravida euismod. Donec rutrum egestas massa. Morbi venenatis dolor ac felis efficitur finibus. Vestibulum sed pellentesque sapien. Donec a rutrum leo, at ornare ligula. Nullam vel feugiat turpis, ac porta felis. Mauris hendrerit tincidunt ante sit amet vestibulum. Cras efficitur porta vulputate.</p>',
      imgLink:
        'https://img.edilportale.com/product-thumbs/b_AMPM_MARAIS_P2yEl6fzY.jpeg',
      additionalInformation:
        '<p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Ut posuere felis et ante pharetra ullamcorper. Maecenas sagittis nisl ac est porta volutpat. Praesent et mollis lorem, vel egestas augue. Aenean euismod auctor dapibus. Nullam sit amet urna erat. Duis euismod diam et nisl molestie dapibus. Sed non ligula vitae risus lacinia viverra id tempor neque. Sed tincidunt ultricies lacinia. Sed sed elit commodo, mattis mauris sed, imperdiet urna. Donec eu interdum ligula. In leo risus, vulputate sed diam nec, porta facilisis elit. Praesent sed sapien ultrices, vulputate nisl a, placerat nulla. Fusce mollis lectus orci. Pellentesque ut enim eleifend lacus dapibus vehicula. Sed mi neque, ullamcorper euismod diam quis, aliquet ultricies eros.</p><p>Pellentesque nunc purus, ultrices vitae nisi id, placerat mollis leo. Aenean egestas orci vel ipsum eleifend dapibus. Suspendisse a pellentesque dui, eu sodales massa. Donec condimentum arcu vitae augue consequat, in sodales enim scelerisque. Sed sodales eros sed porta cursus. Ut pellentesque bibendum tincidunt. Donec a molestie risus, eget consectetur nulla. Sed sed diam erat. Vestibulum velit ligula, eleifend eget sem ut, tristique sagittis neque. Phasellus eget velit nisi. Ut finibus ligula eget lectus aliquet, a ullamcorper velit facilisis.</p>',
    },
    {
      productName: 'Cozy Sofa',
      discountedPrice: 1045.6,
      rawPrice: 1400.0,
      reviewCount: 15,
      reviewStars: 5,
      miniminiDescription: 'Lorem ipsum sit dolor amet',

      miniDescription:
        'Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.',
      fullDescription:
        '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor, nibh vel imperdiet pretium, augue ex rutrum sapien, sit amet rutrum purus libero pretium justo. Curabitur id nisi vitae metus ultricies condimentum. Fusce semper justo ipsum, rutrum rhoncus nulla scelerisque id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor nisl ornare ipsum ultricies, nec fermentum sem tincidunt. Donec arcu purus, tincidunt sed urna a, tristique gravida arcu. Nam ac tincidunt felis. Nam pulvinar ante ut efficitur pellentesque. Cras vel sodales turpis. Nunc fermentum sed sem quis egestas. Nullam ultrices eu diam quis viverra. Proin nec convallis risus. Maecenas efficitur dolor quis lacus scelerisque, vel rutrum nibh vestibulum. Nullam ante lorem, faucibus at convallis ut, ullamcorper sed lacus. In finibus orci eu nibh venenatis, imperdiet rhoncus felis accumsan. Cras a augue bibendum, consectetur enim mattis, vulputate leo.</p><p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Mauris vel facilisis tellus, sit amet cursus turpis. Duis ut consectetur nunc. Nulla viverra nulla vel mi pellentesque efficitur. Cras sit amet efficitur magna. Vestibulum ac ante ac magna feugiat scelerisque. Nullam condimentum gravida euismod. Donec rutrum egestas massa. Morbi venenatis dolor ac felis efficitur finibus. Vestibulum sed pellentesque sapien. Donec a rutrum leo, at ornare ligula. Nullam vel feugiat turpis, ac porta felis. Mauris hendrerit tincidunt ante sit amet vestibulum. Cras efficitur porta vulputate.</p>',
      imgLink:
        'https://img.edilportale.com/product-thumbs/b_Cattelan-Italia_GRETA_REXpceksJ5.jpeg',
      additionalInformation:
        '<p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Ut posuere felis et ante pharetra ullamcorper. Maecenas sagittis nisl ac est porta volutpat. Praesent et mollis lorem, vel egestas augue. Aenean euismod auctor dapibus. Nullam sit amet urna erat. Duis euismod diam et nisl molestie dapibus. Sed non ligula vitae risus lacinia viverra id tempor neque. Sed tincidunt ultricies lacinia. Sed sed elit commodo, mattis mauris sed, imperdiet urna. Donec eu interdum ligula. In leo risus, vulputate sed diam nec, porta facilisis elit. Praesent sed sapien ultrices, vulputate nisl a, placerat nulla. Fusce mollis lectus orci. Pellentesque ut enim eleifend lacus dapibus vehicula. Sed mi neque, ullamcorper euismod diam quis, aliquet ultricies eros.</p><p>Pellentesque nunc purus, ultrices vitae nisi id, placerat mollis leo. Aenean egestas orci vel ipsum eleifend dapibus. Suspendisse a pellentesque dui, eu sodales massa. Donec condimentum arcu vitae augue consequat, in sodales enim scelerisque. Sed sodales eros sed porta cursus. Ut pellentesque bibendum tincidunt. Donec a molestie risus, eget consectetur nulla. Sed sed diam erat. Vestibulum velit ligula, eleifend eget sem ut, tristique sagittis neque. Phasellus eget velit nisi. Ut finibus ligula eget lectus aliquet, a ullamcorper velit facilisis.</p>',
    },
    {
      productName: 'Classic Lamp',
      discountedPrice: 198.75,
      rawPrice: 275.0,
      reviewCount: 20,
      reviewStars: 4,
      miniminiDescription: 'Lorem ipsum sit dolor amet',

      miniDescription:
        'Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.',
      fullDescription:
        '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor, nibh vel imperdiet pretium, augue ex rutrum sapien, sit amet rutrum purus libero pretium justo. Curabitur id nisi vitae metus ultricies condimentum. Fusce semper justo ipsum, rutrum rhoncus nulla scelerisque id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor nisl ornare ipsum ultricies, nec fermentum sem tincidunt. Donec arcu purus, tincidunt sed urna a, tristique gravida arcu. Nam ac tincidunt felis. Nam pulvinar ante ut efficitur pellentesque. Cras vel sodales turpis. Nunc fermentum sed sem quis egestas. Nullam ultrices eu diam quis viverra. Proin nec convallis risus. Maecenas efficitur dolor quis lacus scelerisque, vel rutrum nibh vestibulum. Nullam ante lorem, faucibus at convallis ut, ullamcorper sed lacus. In finibus orci eu nibh venenatis, imperdiet rhoncus felis accumsan. Cras a augue bibendum, consectetur enim mattis, vulputate leo.</p><p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Mauris vel facilisis tellus, sit amet cursus turpis. Duis ut consectetur nunc. Nulla viverra nulla vel mi pellentesque efficitur. Cras sit amet efficitur magna. Vestibulum ac ante ac magna feugiat scelerisque. Nullam condimentum gravida euismod. Donec rutrum egestas massa. Morbi venenatis dolor ac felis efficitur finibus. Vestibulum sed pellentesque sapien. Donec a rutrum leo, at ornare ligula. Nullam vel feugiat turpis, ac porta felis. Mauris hendrerit tincidunt ante sit amet vestibulum. Cras efficitur porta vulputate.</p>',
      imgLink:
        'https://img.edilportale.com/product-thumbs/b_Varaschin_PLINTO_AK8gvpa7gp.jpeg',
      additionalInformation:
        '<p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Ut posuere felis et ante pharetra ullamcorper. Maecenas sagittis nisl ac est porta volutpat. Praesent et mollis lorem, vel egestas augue. Aenean euismod auctor dapibus. Nullam sit amet urna erat. Duis euismod diam et nisl molestie dapibus. Sed non ligula vitae risus lacinia viverra id tempor neque. Sed tincidunt ultricies lacinia. Sed sed elit commodo, mattis mauris sed, imperdiet urna. Donec eu interdum ligula. In leo risus, vulputate sed diam nec, porta facilisis elit. Praesent sed sapien ultrices, vulputate nisl a, placerat nulla. Fusce mollis lectus orci. Pellentesque ut enim eleifend lacus dapibus vehicula. Sed mi neque, ullamcorper euismod diam quis, aliquet ultricies eros.</p><p>Pellentesque nunc purus, ultrices vitae nisi id, placerat mollis leo. Aenean egestas orci vel ipsum eleifend dapibus. Suspendisse a pellentesque dui, eu sodales massa. Donec condimentum arcu vitae augue consequat, in sodales enim scelerisque. Sed sodales eros sed porta cursus. Ut pellentesque bibendum tincidunt. Donec a molestie risus, eget consectetur nulla. Sed sed diam erat. Vestibulum velit ligula, eleifend eget sem ut, tristique sagittis neque. Phasellus eget velit nisi. Ut finibus ligula eget lectus aliquet, a ullamcorper velit facilisis.</p>',
    },
    {
      productName: 'Chic Rug',
      discountedPrice: 320.4,
      rawPrice: 450.0,
      reviewCount: 7,
      reviewStars: 2,
      miniminiDescription: 'Lorem ipsum sit dolor amet',

      miniDescription:
        'Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.',
      fullDescription:
        '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor, nibh vel imperdiet pretium, augue ex rutrum sapien, sit amet rutrum purus libero pretium justo. Curabitur id nisi vitae metus ultricies condimentum. Fusce semper justo ipsum, rutrum rhoncus nulla scelerisque id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor nisl ornare ipsum ultricies, nec fermentum sem tincidunt. Donec arcu purus, tincidunt sed urna a, tristique gravida arcu. Nam ac tincidunt felis. Nam pulvinar ante ut efficitur pellentesque. Cras vel sodales turpis. Nunc fermentum sed sem quis egestas. Nullam ultrices eu diam quis viverra. Proin nec convallis risus. Maecenas efficitur dolor quis lacus scelerisque, vel rutrum nibh vestibulum. Nullam ante lorem, faucibus at convallis ut, ullamcorper sed lacus. In finibus orci eu nibh venenatis, imperdiet rhoncus felis accumsan. Cras a augue bibendum, consectetur enim mattis, vulputate leo.</p><p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Mauris vel facilisis tellus, sit amet cursus turpis. Duis ut consectetur nunc. Nulla viverra nulla vel mi pellentesque efficitur. Cras sit amet efficitur magna. Vestibulum ac ante ac magna feugiat scelerisque. Nullam condimentum gravida euismod. Donec rutrum egestas massa. Morbi venenatis dolor ac felis efficitur finibus. Vestibulum sed pellentesque sapien. Donec a rutrum leo, at ornare ligula. Nullam vel feugiat turpis, ac porta felis. Mauris hendrerit tincidunt ante sit amet vestibulum. Cras efficitur porta vulputate.</p>',
      imgLink:
        'https://www.vitamin-design.com/spree/products/242786/original/S_INTUS_EIO_D_0_cam1.jpg?1685816295',
      additionalInformation:
        '<p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Ut posuere felis et ante pharetra ullamcorper. Maecenas sagittis nisl ac est porta volutpat. Praesent et mollis lorem, vel egestas augue. Aenean euismod auctor dapibus. Nullam sit amet urna erat. Duis euismod diam et nisl molestie dapibus. Sed non ligula vitae risus lacinia viverra id tempor neque. Sed tincidunt ultricies lacinia. Sed sed elit commodo, mattis mauris sed, imperdiet urna. Donec eu interdum ligula. In leo risus, vulputate sed diam nec, porta facilisis elit. Praesent sed sapien ultrices, vulputate nisl a, placerat nulla. Fusce mollis lectus orci. Pellentesque ut enim eleifend lacus dapibus vehicula. Sed mi neque, ullamcorper euismod diam quis, aliquet ultricies eros.</p><p>Pellentesque nunc purus, ultrices vitae nisi id, placerat mollis leo. Aenean egestas orci vel ipsum eleifend dapibus. Suspendisse a pellentesque dui, eu sodales massa. Donec condimentum arcu vitae augue consequat, in sodales enim scelerisque. Sed sodales eros sed porta cursus. Ut pellentesque bibendum tincidunt. Donec a molestie risus, eget consectetur nulla. Sed sed diam erat. Vestibulum velit ligula, eleifend eget sem ut, tristique sagittis neque. Phasellus eget velit nisi. Ut finibus ligula eget lectus aliquet, a ullamcorper velit facilisis.</p>',
    },
    {
      productName: 'Artistic Vase',
      discountedPrice: 162.9,
      rawPrice: 220.0,
      reviewCount: 9,
      reviewStars: 4,
      miniminiDescription: 'Lorem ipsum sit dolor amet',

      miniDescription:
        'Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.',
      fullDescription:
        '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor, nibh vel imperdiet pretium, augue ex rutrum sapien, sit amet rutrum purus libero pretium justo. Curabitur id nisi vitae metus ultricies condimentum. Fusce semper justo ipsum, rutrum rhoncus nulla scelerisque id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor nisl ornare ipsum ultricies, nec fermentum sem tincidunt. Donec arcu purus, tincidunt sed urna a, tristique gravida arcu. Nam ac tincidunt felis. Nam pulvinar ante ut efficitur pellentesque. Cras vel sodales turpis. Nunc fermentum sed sem quis egestas. Nullam ultrices eu diam quis viverra. Proin nec convallis risus. Maecenas efficitur dolor quis lacus scelerisque, vel rutrum nibh vestibulum. Nullam ante lorem, faucibus at convallis ut, ullamcorper sed lacus. In finibus orci eu nibh venenatis, imperdiet rhoncus felis accumsan. Cras a augue bibendum, consectetur enim mattis, vulputate leo.</p><p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Mauris vel facilisis tellus, sit amet cursus turpis. Duis ut consectetur nunc. Nulla viverra nulla vel mi pellentesque efficitur. Cras sit amet efficitur magna. Vestibulum ac ante ac magna feugiat scelerisque. Nullam condimentum gravida euismod. Donec rutrum egestas massa. Morbi venenatis dolor ac felis efficitur finibus. Vestibulum sed pellentesque sapien. Donec a rutrum leo, at ornare ligula. Nullam vel feugiat turpis, ac porta felis. Mauris hendrerit tincidunt ante sit amet vestibulum. Cras efficitur porta vulputate.</p>',
      imgLink:
        'https://www.bludot.com/media/catalog/product/f/d/fd1_lngchr_bh_frontlow-field-lounge-chair-tait-blush_2.jpg?optimize=medium&fit=bounds&height=1200&width=1500&canvas=1500:1200',
      additionalInformation:
        '<p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Ut posuere felis et ante pharetra ullamcorper. Maecenas sagittis nisl ac est porta volutpat. Praesent et mollis lorem, vel egestas augue. Aenean euismod auctor dapibus. Nullam sit amet urna erat. Duis euismod diam et nisl molestie dapibus. Sed non ligula vitae risus lacinia viverra id tempor neque. Sed tincidunt ultricies lacinia. Sed sed elit commodo, mattis mauris sed, imperdiet urna. Donec eu interdum ligula. In leo risus, vulputate sed diam nec, porta facilisis elit. Praesent sed sapien ultrices, vulputate nisl a, placerat nulla. Fusce mollis lectus orci. Pellentesque ut enim eleifend lacus dapibus vehicula. Sed mi neque, ullamcorper euismod diam quis, aliquet ultricies eros.</p><p>Pellentesque nunc purus, ultrices vitae nisi id, placerat mollis leo. Aenean egestas orci vel ipsum eleifend dapibus. Suspendisse a pellentesque dui, eu sodales massa. Donec condimentum arcu vitae augue consequat, in sodales enim scelerisque. Sed sodales eros sed porta cursus. Ut pellentesque bibendum tincidunt. Donec a molestie risus, eget consectetur nulla. Sed sed diam erat. Vestibulum velit ligula, eleifend eget sem ut, tristique sagittis neque. Phasellus eget velit nisi. Ut finibus ligula eget lectus aliquet, a ullamcorper velit facilisis.</p>',
    },
    {
      productName: 'Stylish Clock',
      discountedPrice: 89.45,
      rawPrice: 120.0,
      reviewCount: 5,
      reviewStars: 3,
      miniminiDescription: 'Lorem ipsum sit dolor amet',

      miniDescription:
        'Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.',
      fullDescription:
        '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor, nibh vel imperdiet pretium, augue ex rutrum sapien, sit amet rutrum purus libero pretium justo. Curabitur id nisi vitae metus ultricies condimentum. Fusce semper justo ipsum, rutrum rhoncus nulla scelerisque id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor nisl ornare ipsum ultricies, nec fermentum sem tincidunt. Donec arcu purus, tincidunt sed urna a, tristique gravida arcu. Nam ac tincidunt felis. Nam pulvinar ante ut efficitur pellentesque. Cras vel sodales turpis. Nunc fermentum sed sem quis egestas. Nullam ultrices eu diam quis viverra. Proin nec convallis risus. Maecenas efficitur dolor quis lacus scelerisque, vel rutrum nibh vestibulum. Nullam ante lorem, faucibus at convallis ut, ullamcorper sed lacus. In finibus orci eu nibh venenatis, imperdiet rhoncus felis accumsan. Cras a augue bibendum, consectetur enim mattis, vulputate leo.</p><p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Mauris vel facilisis tellus, sit amet cursus turpis. Duis ut consectetur nunc. Nulla viverra nulla vel mi pellentesque efficitur. Cras sit amet efficitur magna. Vestibulum ac ante ac magna feugiat scelerisque. Nullam condimentum gravida euismod. Donec rutrum egestas massa. Morbi venenatis dolor ac felis efficitur finibus. Vestibulum sed pellentesque sapien. Donec a rutrum leo, at ornare ligula. Nullam vel feugiat turpis, ac porta felis. Mauris hendrerit tincidunt ante sit amet vestibulum. Cras efficitur porta vulputate.</p>',
      imgLink:
        'https://images.whoppah.com/products/wCTpN7x2-/ASWdQqPrO/1920x1279/1-of-6-emc-mbler-chairs.jpeg?width=1280',
      additionalInformation:
        '<p>Curabitur auctor lacus eget lorem blandit, ac tempus ante euismod. Morbi nec odio in sem elementum hendrerit id vel ipsum. In nec nibh vel orci porta pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec tristique diam, ac vulputate massa. Aliquam massa magna, tincidunt et ultrices tempor, scelerisque nec sem. Sed auctor faucibus facilisis. Nulla vel ligula non mauris lobortis pretium. Donec sit amet volutpat nisl, sed ultrices turpis. Curabitur posuere erat nunc, eget volutpat turpis aliquet quis.</p><p>Ut posuere felis et ante pharetra ullamcorper. Maecenas sagittis nisl ac est porta volutpat. Praesent et mollis lorem, vel egestas augue. Aenean euismod auctor dapibus. Nullam sit amet urna erat. Duis euismod diam et nisl molestie dapibus. Sed non ligula vitae risus lacinia viverra id tempor neque. Sed tincidunt ultricies lacinia. Sed sed elit commodo, mattis mauris sed, imperdiet urna. Donec eu interdum ligula. In leo risus, vulputate sed diam nec, porta facilisis elit. Praesent sed sapien ultrices, vulputate nisl a, placerat nulla. Fusce mollis lectus orci. Pellentesque ut enim eleifend lacus dapibus vehicula. Sed mi neque, ullamcorper euismod diam quis, aliquet ultricies eros.</p><p>Pellentesque nunc purus, ultrices vitae nisi id, placerat mollis leo. Aenean egestas orci vel ipsum eleifend dapibus. Suspendisse a pellentesque dui, eu sodales massa. Donec condimentum arcu vitae augue consequat, in sodales enim scelerisque. Sed sodales eros sed porta cursus. Ut pellentesque bibendum tincidunt. Donec a molestie risus, eget consectetur nulla. Sed sed diam erat. Vestibulum velit ligula, eleifend eget sem ut, tristique sagittis neque. Phasellus eget velit nisi. Ut finibus ligula eget lectus aliquet, a ullamcorper velit facilisis.</p>',
    },
  ];

  getAllProducts(): Product[] {
    return this.products;
  }
  create(createProductDto: CreateProductDto) {
    this.products.push(createProductDto);
    return { message: 'Ürün başarıyla kaydedildi!', product: createProductDto };
  }
}
